[package]
name = "flare-decoders"
version.workspace = true
edition.workspace = true

[dependencies]
flare-common = { workspace = true }
alloy.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
chrono.workspace = true
thiserror.workspace = true
